version: 2

updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

    groups:
      bun-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

    labels:
      - "dependencies"
      - "bun"

    commit-message:
      prefix: "chore"
      include: "scope"
