name: Code Quality
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  commit-lint:
    name: Lint commit messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
  quality-checks:
    name: ${{ matrix.task.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - name: "Lint and Format"
            command: "bunx turbo lint"
          - name: "Test build"
            command: "bunx turbo build"
          - name: "Type Check"
            command: "bunx typedoc --options ./.config/typedoc.json"
          - name: "Vulnerability Check"
            command: 'bun audit --audit-level=moderate'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run ${{ matrix.task.name }}
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
        run: ${{ matrix.task.command }}
