name: Unit & Integration Tests

on:
  pull_request:
  push:

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    name: Test
    runs-on: ubuntu-latest
    services:
      backend-postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.17.0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
            bun install
            bunx playwright install

      - name: Set up Database
        env:
          # secretlint-disable-next-line
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
        run: |
          bunx turbo migrate

      - name: Run Tests
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          # secretlint-disable-next-line
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
        run: bunx turbo test
